
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    

    def input_processing():
        with open("input.txt", "r") as f:
            data = f.read()

        parts = data.split(":")

        # SELECT ATTRIBUTES LIST
        select_attributes = parts[1].split('\n')
        select_attributes.pop(0)
        select_attributes.pop(len(select_attributes)-1)
        select_attributes = select_attributes[0].split(',')
        for i in range(len(select_attributes)):
            select_attributes[i] = select_attributes[i].strip()

        # NUMBER OF GROUPING VARIABLES
        numberOfGroupingVariables = parts[2].split('\n')[1]
        # print(numberOfGroupingVariables)

        # GROUPING VARIABLES LIST
        groupingvariables = parts[3].split('\n')[1]
        groupingattributes = list(map(lambda x: x.strip(),groupingvariables.split(',')))

        # VECTOR OF AGGREGATE FUNCTIONS
        vectorOfAggregateFunctions = parts[4].split('\n')[1]
        vectorOfAggregateFunctions = vectorOfAggregateFunctions.split(',')
        for i in range(len(vectorOfAggregateFunctions)):
            vectorOfAggregateFunctions[i] = vectorOfAggregateFunctions[i].strip()

        # hset = set()
        # res = []
        # for i in range(len(vectorOfAggregateFunctions)):
        #     attr = vectorOfAggregateFunctions[i].split("_")[0]
        #     if attr not in hset:
        #         tmp = [vectorOfAggregateFunctions[i]]
        #         hset.add(attr)
        #         for j in range(i+1, len(vectorOfAggregateFunctions)):
        #             checkattr = vectorOfAggregateFunctions[j].split("_")[0]
        #             if checkattr == attr:
        #                 tmp.append(vectorOfAggregateFunctions[j])
        #         res.append(tmp)

        # vectorOfAggregateFunctions = res

        hset = {}
        for i in range(len(vectorOfAggregateFunctions)):
            attr_agg = vectorOfAggregateFunctions[i].split("_",1)
            attr, agg  = attr_agg[0], attr_agg[1]
            if attr not in hset:
                hset[attr] = [agg]
            else:
                if not agg in hset[attr]:
                    hset[attr].append(agg)

        vectorOfAggregateFunctions = hset

        # PREDICATE LIST
        predicateList = parts[5].split('\n')
        predicateList.pop(0)
        predicateList.pop(len(predicateList)-1)

        def predicate_list_splitting_by_ops(s):
            ops = [' AND ', ' OR ', ' NOT ']
            andsplitlist = s.split(ops[0]) # splitting by AND operator
            res = []
            for andsplit in andsplitlist:
                orsplitlist = andsplit.split(ops[1])
                for orsplit in orsplitlist:
                    notsplitlist = orsplit.split(ops[2])
                    for notsplit in notsplitlist:
                        res.append(notsplit)
            for r in range(len(res)):
                res[r] = res[r].strip()
            return res

        def predicate_list_splitting_by_types(s):
            types = ['>=', '<=', "!=", '=', '>', "<"]

            reslist = []
            for t in types:
                if t in s:
                    reslist = s.split(t)
                    break 
            tmp = reslist[0].split('.')
            tmp2 = reslist[1]
            reslist = []
            for i in range(len(tmp)):
                reslist.append(tmp[i])
            reslist.append(tmp2)
            return reslist

        predicatehashmap = {}
        # for p in predicateList:
        #     tmplist = predicate_list_splitting_by_ops(p)
        #     for t in tmplist:
        #         condition = t.split(".")
        #         if condition[0] in predicatehashmap:
        #             predicatehashmap[condition[0]].append(condition[1])
        #         else:
        #             predicatehashmap[condition[0]] = [condition[1]]  
        for p in predicateList:
            #tmplist = predicate_list_splitting_by_ops(p)
            cond = p.split(".")
            predicatehashmap[cond[0]] = p


        # HAVING CLAUSE
        havingClause = parts[6].split('\n')[1]

        # print(select_attributes)
        # print(numberOfGroupingVariables)
        # print(groupingattributes)
        # print(vectorOfAggregateFunctions)
        # print(predicatehashmap)
        # print(havingClause)

        return [select_attributes, numberOfGroupingVariables, groupingattributes, vectorOfAggregateFunctions, predicatehashmap, havingClause]

    def aggrfunctioncompute(s):
        return s.split("_")

    def get_col_op_value(cond):
        res = cond.split('.')
        tmp = res[1]
        operator = ''
        for op in ["!=", ">=", "<=", ">", "<", "="]:
            if op in tmp:
                operator = op
                break 
        tmp = tmp.split(op)
        col = tmp[0]
        val = tmp[1]

        if val.isdigit():
            val = int(val)

        if isinstance(val, str):
            val = val.strip("'")

        return [col, op, val]

    def evalandcond(row, cond):
        evalconds = cond.split(' AND ')
        finalbool = True 

        for cond in evalconds:
            [col, op, val] = get_col_op_value(cond)
            match op:
                case "!=":
                    finalbool = finalbool and row[col] != val
                case ">=":
                    finalbool = finalbool and row[col] >= val
                case "<=":
                    finalbool = finalbool and row[col] <= val
                case ">":
                    finalbool = finalbool and row[col] > val
                case "<":
                    finalbool = finalbool and row[col] < val
                case "=":
                    finalbool = finalbool and row[col] == val
                case _:
                    print(f"Unknown command: {tmpoperator}")
        return finalbool

    def evaluateConditions(row, predlistforgroupingvariable):
        # split by OR'S
        evalconds = predlistforgroupingvariable.split(' OR ')
        finalbool = False
        for cond in evalconds:
            # cond can contain ANDS now
            finalbool = finalbool or evalandcond(row, cond)
        return finalbool
    
    select_attributes, numberOfGroupingVariables, groupingattributes, vectorOfAggregateFunctions, predicatehashmap, havingClause = input_processing()

    '''
    key: specific group value -> 
        {
            attr_1: attr_1 value
            ...
            attr_n : attr_n value
            grouping variable -> [list of aggr funcs respective to that gv]
        }
    '''
    # THIS PASS IS FOR CREATING THE MF STRUCT
    mfstructdict = {}
    for row in cur:
        # Create the key for MFStruct - Represents the value for each unique combo of attributes
        groupingattributekey = tuple(row[attr] for attr in groupingattributes)

        # If our key is not in MFStruct
        if groupingattributekey not in mfstructdict:

            # We create a new map
            aggrfuncmap = {}

            # We first populate it with the values of group attributes
            # such as cust = 'Jake"
            for attr in groupingattributes:
                aggrfuncmap[attr] = row[attr]

            # For each grouping variable we map it to a list of aggregate functions
            for key in vectorOfAggregateFunctions:
                aggrfuncmap[key] = [0] * len(vectorOfAggregateFunctions[key])
                for key2 in range(0,len(vectorOfAggregateFunctions[key])):
                    tmp = aggrfunctioncompute(vectorOfAggregateFunctions[key][key2])
                    if tmp[0] == "min":
                        aggrfuncmap[key][key2] = float('inf')
                    if tmp[0] == 'max':
                        aggrfuncmap[key][key2] = float('-inf')
                    if tmp[0] == 'avg':
                        # [Total Sum, Count, Avg]
                        aggrfuncmap[key][key2] = [0,0,0]
                    
            mfstructdict[groupingattributekey] = aggrfuncmap

    for key in vectorOfAggregateFunctions:
        # the predicate list for that grouping variable
        predlistforgroupingvariable = predicatehashmap[key] 
        cur.execute("SELECT * FROM sales")
        for row in cur:      
            #UPDATE THE MFSTRUCTDICT
            #update the grouping variables aggr funcs
            for groupingattributekey in mfstructdict:
                rowchecktuple = tuple(row[attr] for attr in groupingattributes)
                if rowchecktuple == groupingattributekey:
                    if evaluateConditions(row, predlistforgroupingvariable):
                        # the aggregate functions from that grouping variable
                        aggrfuncs = vectorOfAggregateFunctions[key]

                        for index in range(len(aggrfuncs)):
                            function, attribute = aggrfunctioncompute(aggrfuncs[index])
                            # min, max, avg, sum, count
                            if function == "count":
                                mfstructdict[groupingattributekey][key][index] +=1
                            elif function == "sum":
                                mfstructdict[groupingattributekey][key][index] += row[attribute]
                            elif function == "min":
                                mfstructdict[groupingattributekey][key][index] = min(mfstructdict[groupingattributekey][key][index], row[attribute])
                            elif function == "max":
                                mfstructdict[groupingattributekey][key][index] = max(mfstructdict[groupingattributekey][key][index], row[attribute])
                            else:
                                num, denom, avg = mfstructdict[groupingattributekey][key][index]
                                num += row[attribute]
                                denom += 1
                                avg = num/denom
                                mfstructdict[groupingattributekey][key][index] = [num, denom, avg]

    for grouping_key, aggrfuncmap in mfstructdict.items():
        row = {attr: aggrfuncmap[attr] for attr in groupingattributes}
        
        for gv_key, func_values in aggrfuncmap.items():
            if gv_key in groupingattributes:
                continue  # already added
            flat_values = []
            for val in func_values:
                if isinstance(val, list) and len(val) == 3:  # avg: [sum, count, avg]
                    flat_values.append(val[2])  # use the average
                else:
                    flat_values.append(val)
            row[gv_key] = flat_values
        _global.append(row)

    

    
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    