
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    mfstruct = {}
    group = ('prod', 'cust')
    
    #Creating the mfstruct
    for row in cur:
        current_group = tuple([row[attr] for attr in group])
        mfstruct[current_group] = dict()
        for attr in group:
            mfstruct[current_group][attr] = row[attr]
        mfstruct[current_group]['1_min_quant'] = float('inf')
        mfstruct[current_group]['1_sum_quant'] = 0
        mfstruct[current_group]['1_avg_quant'] = [0,0,0]
        mfstruct[current_group]['3_avg_quant'] = [0,0,0]
        mfstruct[current_group]['3_sum_quant'] = 0
        mfstruct[current_group]['2_min_quant'] = float('inf')
        mfstruct[current_group]['2_sum_quant'] = 0
        mfstruct[current_group]['2_avg_quant'] = [0,0,0]

    

    #Predicates
    cur.execute("SELECT * FROM sales")
    for row in cur:
        for groupingattributekey in mfstruct:
            rowchecktuple = tuple(row[attr] for attr in group)
            
            if rowchecktuple == groupingattributekey:
                if row['state']=='NJ' :
                    mfstruct[groupingattributekey]['2_min_quant'] = min(mfstruct[groupingattributekey]['2_min_quant'], row['quant'])
                    mfstruct[groupingattributekey]['2_sum_quant'] += row['quant']
                    num, denom, avg = mfstruct[groupingattributekey]['2_avg_quant']
                    num += row['quant']
                    denom += 1
                    avg = num/denom
                    mfstruct[groupingattributekey]['2_avg_quant'] = [num, denom, avg]
                if row['state']=='NJ' and row['quant'] > 100:
                    mfstruct[groupingattributekey]['1_min_quant'] = min(mfstruct[groupingattributekey]['1_min_quant'], row['quant'])
                    mfstruct[groupingattributekey]['1_sum_quant'] += row['quant']
                    num, denom, avg = mfstruct[groupingattributekey]['1_avg_quant']
                    num += row['quant']
                    denom += 1
                    avg = num/denom
                    mfstruct[groupingattributekey]['1_avg_quant'] = [num, denom, avg]
                if row['state']=='CT':
                    num, denom, avg = mfstruct[groupingattributekey]['3_avg_quant']
                    num += row['quant']
                    denom += 1
                    avg = num/denom
                    mfstruct[groupingattributekey]['3_avg_quant'] = [num, denom, avg]
                    mfstruct[groupingattributekey]['3_sum_quant'] += row['quant']
    



    #Having clause
    for groupingattributekey in mfstruct:
        if not (mfstruct['groupingattributekey']['1_sum_quant'] > 2 * mfstruct['groupingattributekey']['2_sum_quant'] or mfstruct['groupingattributekey']['1_avg_quant'] > mfstruct['groupingattributekey']['3_avg_quant']):
            del mfstruct[groupingattributekey]
    
    
    print(mfstruct)
    return 1
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    