
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    column_names = [desc[0] for desc in cur.description]
    
    mfstruct = {}
    group = ('cust', 'month')
    
    for column in group:
        if column not in column_names:
            raise ValueError("Unknown Column")
    #Creating the mfstruct
    for row in cur:
        current_group = tuple([row[attr] for attr in group])
        mfstruct[current_group] = dict()
        for attr in group:
            mfstruct[current_group][attr] = row[attr]
        mfstruct[current_group]['1_max_quant'] = float('-inf')
        mfstruct[current_group]['2_max_quant'] = float('-inf')
        mfstruct[current_group]['3_max_quant'] = float('-inf')

    

    #Predicates
    #We just check the groups if the grouping variable doesn't have a predicate
    cur.execute("SELECT * FROM sales")
    for row in cur:
        rowchecktuple = tuple(row[attr] for attr in group)
        for groupingattributekey in mfstruct:
            try:
               #Grouping variable 1
               if rowchecktuple == groupingattributekey and (row['year'] == 2017):
                   mfstruct[groupingattributekey]['1_max_quant'] = max(mfstruct[groupingattributekey]['1_max_quant'], row['quant'])
               #Grouping variable 2
               if rowchecktuple == groupingattributekey and (row['year'] == 2018):
                   mfstruct[groupingattributekey]['2_max_quant'] = max(mfstruct[groupingattributekey]['2_max_quant'], row['quant'])
               #Grouping variable 3
               if rowchecktuple == groupingattributekey and (row['year'] == 2019):
                   mfstruct[groupingattributekey]['3_max_quant'] = max(mfstruct[groupingattributekey]['3_max_quant'], row['quant'])
 
            except KeyError:
                raise ValueError("A grouping variable has an unknown column")



    #Having clause
    try:
        for groupingattributekey in list(mfstruct):
            if not (mfstruct[groupingattributekey]['1_max_quant'] > mfstruct[groupingattributekey]['2_max_quant'] and mfstruct[groupingattributekey]['1_max_quant'] > mfstruct[groupingattributekey]['3_max_quant']):
                del mfstruct[groupingattributekey]
    except KeyError:
        raise ValueError('The having clause references an unknown attribute')


    #Projection
    for groupingattributekey, aggrfuncmap in mfstruct.items():
        row = dict()
        
        row['cust'] = aggrfuncmap['cust']
        row['month'] = aggrfuncmap['month']
        row['1_max_quant'] = aggrfuncmap['1_max_quant']
        row['2_max_quant'] = aggrfuncmap['2_max_quant']
        row['3_max_quant'] = aggrfuncmap['3_max_quant']

        _global.append(row)
    
    
    # print(mfstruct)
    # return 1
    # print(mfstruct[(11,'Grapes')])
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    