
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    column_names = [desc[0] for desc in cur.description]
    
    mfstruct = {}
    group = ('month', 'prod', 'year')
    
    for column in group:
        if column not in column_names:
            raise ValueError("Unknown Column")
    #Creating the mfstruct
    for row in cur:
        current_group = tuple([row[attr] for attr in group])
        mfstruct[current_group] = dict()
        for attr in group:
            mfstruct[current_group][attr] = row[attr]
        mfstruct[current_group]['1_avg_quant'] = [0,0,0]
        mfstruct[current_group]['2_avg_quant'] = [0,0,0]
        mfstruct[current_group]['3_avg_quant'] = [0,0,0]

    

    #Predicates
    #We just check the groups if the grouping variable doesn't have a predicate
    cur.execute("SELECT * FROM sales")
    for row in cur:
        
        rowchecktuple = tuple(row[attr] for attr in group)
        for groupingattributekey in mfstruct:
            try:
               #Grouping variable 1
               if mfstruct[groupingattributekey]['prod'] == row['prod'] and mfstruct[groupingattributekey]['month'] == row['month'] and mfstruct[groupingattributekey]['year'] == row['year']:
                   num, denom, avg = mfstruct[groupingattributekey]['1_avg_quant']
                   num += row['quant']
                   denom += 1
                   avg = num/denom
                   mfstruct[groupingattributekey]['1_avg_quant'] = [num, denom, avg]
               #Grouping variable 2
               if mfstruct[groupingattributekey]['prod'] == row['prod'] and mfstruct[groupingattributekey]['year'] == row['year']:
                   num, denom, avg = mfstruct[groupingattributekey]['2_avg_quant']
                   num += row['quant']
                   denom += 1
                   avg = num/denom
                   mfstruct[groupingattributekey]['2_avg_quant'] = [num, denom, avg]
               #Grouping variable 3
               if rowchecktuple == groupingattributekey and (row['state'] == 'NJ'):
                   num, denom, avg = mfstruct[groupingattributekey]['3_avg_quant']
                   num += row['quant']
                   denom += 1
                   avg = num/denom
                   mfstruct[groupingattributekey]['3_avg_quant'] = [num, denom, avg]
                   if row["prod"] == "Grapes" and row["month"] == 5 and row["state"] == "NJ" and row["year"] == 2020:
                       print(row)
                       print(mfstruct[groupingattributekey]) 
 
            except KeyError:
                raise ValueError("A grouping variable has an unknown column")



    #Having clause


    for groupingattribute in mfstruct:
        if "Grapes" in groupingattribute and 5 in groupingattribute:
            print(mfstruct[groupingattribute])
    #Projection
    for groupingattributekey, aggrfuncmap in mfstruct.items():
        row = dict()
        
        row['prod'] = aggrfuncmap['prod']
        row['month'] = aggrfuncmap['month']
        row['year'] = aggrfuncmap['year']
        row['1_avg_quant'] = aggrfuncmap['1_avg_quant'][2]
        row['2_avg_quant'] = aggrfuncmap['2_avg_quant'][2]
        row['3_avg_quant'] = aggrfuncmap['3_avg_quant'][2]

        _global.append(row)
    
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    