
import os
import psycopg2
import psycopg2.extras
import tabulate
from dotenv import load_dotenv

# DO NOT EDIT THIS FILE, IT IS GENERATED BY generator.py

def query():
    load_dotenv()

    user = os.getenv('USER')
    password = os.getenv('PASSWORD')
    dbname = os.getenv('DBNAME')

    conn = psycopg2.connect("dbname="+dbname+" user="+user+" password="+password,
                            cursor_factory=psycopg2.extras.DictCursor)
    cur = conn.cursor()
    cur.execute("SELECT * FROM sales")
    
    _global = []
    
    column_names = [desc[0] for desc in cur.description]
    
    mfstruct = {}
    group = ('month', 'cust')
    
    for column in group:
        if column not in column_names:
            raise ValueError("Unknown Column")
    #Creating the mfstruct
    for row in cur:
        current_group = tuple([row[attr] for attr in group])
        mfstruct[current_group] = dict()
        for attr in group:
            mfstruct[current_group][attr] = row[attr]
        mfstruct[current_group]['1_sum_quant'] = 0

    

    #Predicates
    #We just check the groups if the grouping variable doesn't have a predicate
    cur.execute("SELECT * FROM sales")
    for row in cur:
        rowchecktuple = tuple(row[attr] for attr in group)
        for groupingattributekey in mfstruct:
            try:
               #Grouping variable 1
               if rowchecktuple == groupingattributekey and (row['state'] == 'CT'):
                   mfstruct[groupingattributekey]['1_sum_quant'] += row['quant']
 
            except KeyError:
                raise ValueError("A grouping variable has an unknown column")



    #Having clause



    #Projection
    for groupingattributekey, aggrfuncmap in mfstruct.items():
        row = dict()
        
        row['cust'] = aggrfuncmap['cust']
        row['month'] = aggrfuncmap['month']
        row['1_sum_quant'] = aggrfuncmap['1_sum_quant']

        _global.append(row)
    
    
    return tabulate.tabulate(_global,
                        headers="keys", tablefmt="psql")

def main():
    print(query())
    
if "__main__" == __name__:
    main()
    